// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;


//import org.ejml.equation.Variable;

import edu.wpi.first.wpilibj.RobotBase;

/**
 * Do NOT add any static variables to this class, or any initialization at all.
 * Unless you know what you are doing, do not modify this file except to
 * change the parameter class to the startRobot call.
 */
public final class Main {
  private Main() {
  }

  /**
   * Main initialization function. Do not perform any initialization here.
   *
   * <p>If you change your main robot class, change the parameter type.
   */
  public static void main(String... args) {
    RobotBase.startRobot(Robot::new);
    // System.out.printf("we will not use 'hello robot!'");
    // double xxx = Math.sqrt(4);
    // float yyy = Math.floorMod(-15, 2);
    // float zzz = Float.NaN;
    // final int ddd = -15 % 2;
    // var kkk = 0;
    // var message = "I'm kevin!";
    // //message = 0;
    // LocalDate today = LocalDate.now();  //java.time.LocalDate today = java.time.LocalDate.now();

    


    
  }
}
