// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Constants;
import frc.robot.RobotContainer;
import frc.robot.Constants.ConveyorConst;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Chassis;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutonomousCmd extends CommandBase {

    
    Timer m_timer=new Timer();
    // double ritme=0;
    // int phase=1;
    // boolean slowing=false;
    // double speed;
    // boolean intakeON=false;
    // boolean outakeON=false;
    // boolean Abutton;
    // boolean Bbutton;
  
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final Chassis m_chassis;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public AutonomousCmd(Chassis subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_chassis = subsystem;
        addRequirements(m_chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_timer.reset();
        m_timer.start();                
        // intakeON=false;
        // outakeON=false;       
        // phase=1; 

        //m_chassis.encoderReset();  
        //RobotContainer.getInstance().m_intake.setIntakeMotor(0.0);
        System.out.println("AutonomousDrive Initializing!");
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
      
        System.out.println("AutonomousDrive Executing!");
      
    //     //m_chassis.moveForward(25.0);
    //    if (!m_chassis.getLimitSwitch().get()) // limitswich is false (not triggered)
    //    m_chassis.moveForward(true);  
    //    else // limitswich is true (triggered)
    //    RobotContainer.getInstance().m_conveyor.setConveyMotor(ConveyorConst.CONVEY_STRENGTH);     

       if (m_timer.get()<=Constants.AUTO_CONEYOR_TIME) 
            RobotContainer.getInstance().m_conveyor.setConveyMotor(ConveyorConst.CONVEY_STRENGTH);   
       else if (m_timer.get() > Constants.AUTO_CONEYOR_TIME && m_timer.get()<=Constants.AUTO_TIME) 
            {
                RobotContainer.getInstance().m_conveyor.stop();   
                m_chassis.moveBackward(true);            
            }
       else 
            m_chassis.moveBackward(false);
           

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_chassis.stop();
        System.out.println("AutonomousDrive ended!");
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
        
        // 1 - return limitswitch status:
        //return RobotContainer.getInstance().m_chassis.getLimitSwitch1().get();

        // 2 - return distance:
        //return RobotContainer.getInstance().m_chassis.getDistance()>=distance; 
        
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
